const TODOS = {
  LOADING: 'TODOS_LOADING',
  FETCH_SUCCESS: 'TODOS_FETCH_SUCCESS',
  FETCH_FAILED: 'TODOS_FETCH_FAILED'
};

const TODO_DETAIL = {
  LOADING: 'TODO_DETAIL_LOADING',
  FETCH_SUCCESS: 'TODO_DETAIL_FETCH_SUCCESS',
  FETCH_FAILED: 'TODO_DETAIL_FETCH_FAILED'
}

export { TODOS , TODO_DETAIL };
